pds/cvprof/urls.py
from django.urls import path
from . import views

app_name = 'cvprof'

urlpatterns = [
    path('<int:id>', views.index, name = "index"),
    path('', views.index, name = "index"),
    path('profiles', views.profile, name = "profiles"),
    path('addprof', views.addprofile, name = "addprof" ),
]

pds/pds/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('prof/', include('cvprof.urls')),
]

pds/cvprof/models.py
from django.db import models

# Create your models here.


class CVModel(models.Model):
    fullname = models.CharField(max_length=255)
    position = models.CharField(max_length=50)
    address = models.CharField(max_length=500)
    email = models.EmailField(max_length=254)
    contact = models.IntegerField()
    skill = models.CharField(max_length=50,null=True)
    firstskills = models.CharField(max_length=50,null=True)
    secondskills = models.CharField(max_length=50,null=True)
    thirdkills = models.CharField(max_length=50,null=True)
    fourthskills =models.CharField(max_length=50, null=True)
    language =models.CharField(max_length=50, null=True)
    firstlanguage =models.CharField(max_length=50, null=True)
    secondlanguage =models.CharField(max_length=50, null=True)
    thirdlanguage =models.CharField(max_length=50, null=True)
    work_experience = models.CharField(max_length=500,null=True)
    firstwork_experience = models.CharField(max_length=500,null=True)
    workexper_descrip = models.TextField(null=True)
    second_experience = models.CharField(max_length=500,null=True)
    third_experience = models.CharField(max_length=500,null=True)
    education = models.CharField(max_length=250, null=True)
    primaryschool = models.CharField(max_length=250, null=True)
    secondaryschool = models.CharField(max_length=250, null=True)
    tertiaryschool = models.CharField(max_length=250, null=True)

    def __str__(self):
        return self.fullname

pds/cvprof/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import CVModel

# Create your views here.
def index(request,id=1):
    data = CVModel.objects.get(pk=id)
    return render(request,'cvprof/index.html',{'data':data})

def profile(request):
    context = {}
    data = CVModel.objects.all()
    context = {'records': data}
    return render(request,'cvprof/prof.html',context)

def addprofile(request):
    context = {}
    data = CVModel.objects.all()
    context = {'records': data}
    return render(request,'cvprof/addprof.html',context)

pds/cvprof/templates/cvprof/addprof.html
<!DOCTYPE html>
<!-- saved from url=(0057)https://www.w3schools.com/w3css/tryw3css_templates_cv.htm -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Django App!</title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="/static/cvprof/src/w3.css">
<link rel="stylesheet" href="/static/cvprof/css.css">
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
</style>
</head>
<body class="w3-light-grey">

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
    <div class="w3-row">      
        <div class="w3-container">
            <div class="w3-container  w3-card w3-white w3-margin-bottom">
                <div class="w3-bar w3-padding-small">
                  <a href="/prof/" class="w3-bar-item w3-button w3-text-indigo"> <i class="fa fa-address-book fa-fw w3-margin-left w3-large " aria-hidden="true"></i>Default Profile</a>
                  <a href="/prof/addprof" class="w3-bar-item w3-button w3-text-indigo">New CV</a>
                  <a href="#" class="w3-bar-item w3-button">Link 2</a>
                  <a href="#" class="w3-bar-item w3-button">Link 3</a>
                </div>
                
            </div>     
        </div>

        <div class="w3-container">
            <div class="w3-container  w3-card w3-white">
               <h2> ADD CV Profile  </h2>
             
               <form action="/prof/addprof" method="post">
                    <input type="hidden" name="csrfmiddlewaretoken" value="s3ghq41M7B0eIBdA5GRiU4VKIURnijSsVxzUEqpLxQOoLr6V0PQtyBMcNfc6Zxvf">
                    <tr>
    <th><label for="id_fullname">Fullname:</label></th>
    <td>
      
      <input type="text" name="fullname" maxlength="255" required id="id_fullname">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_address">Address:</label></th>
    <td>
      
      <input type="text" name="address" maxlength="500" required id="id_address">
      
      
    </td>
  </tr>

  <tr>
    <th><label for="id_email">Email:</label></th>
    <td>
      
      <input type="email" name="email" required id="id_email">
      
      
        
      
    </td>
  </tr>  
                    <button type="submit">Submit</button>
               </form>
                
                <p>&nbsp;</p>
                
            </div>     
        </div>

    </div>

  <!-- End Grid -->
  </div>

  <!-- End Page Container -->
</div>

<footer class="w3-container w3-indigo w3-center w3-margin-top">
  <p>Find me on social media.</p>
  <i class="fa fa-facebook-official w3-hover-opacity"></i>
  <i class="fa fa-instagram w3-hover-opacity"></i>
  <i class="fa fa-snapchat w3-hover-opacity"></i>
  <i class="fa fa-pinterest-p w3-hover-opacity"></i>
  <i class="fa fa-twitter w3-hover-opacity"></i>
  <i class="fa fa-linkedin w3-hover-opacity"></i>
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>


</body>

</html>

pds/cvprof/templates/cvprof/index.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0057)https://www.w3schools.com/w3css/tryw3css_templates_cv.htm -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>My Final Template</title>

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'cvprof/src/w3.css' %}">
<link rel="stylesheet" href="{% static 'cvprof/src/css.css' %}">
<link rel="stylesheet" href="{% static 'cvprof/src/f/css/font-awesome.min.css' %}">

<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
</style>
</head>
<body class="w3-light-grey">

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third">
    
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <img src="{% static 'cvprof/src/dakota.avif' %}" style="width:100%" alt="Avatar">
          <div class="w3-display-bottomleft w3-container w3-text-black">
            <h2>{{ data.fullname }}</h2>
          </div>
        </div>
        <div class="w3-container">
          <p><i class="fa fa-briefcase fa-fw w3-margin-right w3-large w3-text-indigo"></i>{{ data.position }}</p>
          <p><i class="fa fa-home fa-fw w3-margin-right w3-large w3-text-indigo"></i>{{ data.address }}</p>
          <p><i class="fa fa-envelope fa-fw w3-margin-right w3-large w3-text-indigo"></i>{{ data.email }}</p>
          <p><i class="fa fa-phone fa-fw w3-margin-right w3-large w3-text-indigo"></i>{{ data.contact }}</p>
          <hr>

          <p class="w3-large"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-indigo"></i>{{ data.skill }}</b></p>
          <p>{{ data.firstskills }}</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-indigo" style="width:90%">90%</div>
          </div>
          <p>{{ data.secondskills }}</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-indigo" style="width:80%">
              <div class="w3-center w3-text-white">80%</div>
            </div>
          </div>
          <p>{{ data.thirdkills }}</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-indigo" style="width:75%">75%</div>
          </div>
          <p>{{ data.fourthskills }}</p>
          <div class="w3-light-grey w3-round-xlarge w3-small">
            <div class="w3-container w3-center w3-round-xlarge w3-indigo" style="width:50%">50%</div>
          </div>
          <br>

          <p class="w3-large w3-text-theme"><b><i class="fa fa-globe fa-fw w3-margin-right w3-text-indigo"></i>{{ data.language }}</b></p>
          <p>{{ data.firstlanguage }}</p>
          <div class="w3-light-grey w3-round-xlarge">
            <div class="w3-round-xlarge w3-indigo" style="height:24px;width:100%"></div>
          </div>
          <p>{{ data.secondlanguage }}</p>
          <div class="w3-light-grey w3-round-xlarge">
            <div class="w3-round-xlarge w3-indigo" style="height:24px;width:55%"></div>
          </div>
          <p>{{ data.thirdlanguage }}</p>
          <div class="w3-light-grey w3-round-xlarge">
            <div class="w3-round-xlarge w3-indigo" style="height:24px;width:25%"></div>
          </div>
          <br>
        </div>
      </div><br>

    <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-twothird">

      <div class="w3-container">
        <div class="w3-container  w3-card w3-white w3-margin-bottom">
            <div class="w3-bar w3-padding-small">
              <a href="{% url 'cvprof:profiles' %}" class="w3-bar-item w3-button w3-text-indigo"> <i class="fa fa-address-book fa-fw w3-margin-left w3-large " aria-hidden="true"></i>Lists Of Names</a>
              <a href="http://127.0.0.1:8000/admin/cvprof/cvmodel/add/" class="w3-bar-item w3-button w3-text-indigo">Add New Cv Model</a>
              <a href="http://127.0.0.1:8000/admin/" class="w3-bar-item w3-button w3-text-indigo">Admin Page</a>
              <a href="/prof/addprof" class="w3-bar-item w3-button w3-text-indigo">New CV</a>
            </div>
            
        </div>     
    </div>
      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-suitcase fa-fw w3-margin-right w3-xxlarge w3-text-indigo"></i> {{ data.work_experience }}</h2>
        <div class="w3-container">
          <h5 class="w3-opacity"><b>{{ data.firstwork_experience }}</b></h5>
          <h6 class="w3-text-indigo"><i class="fa fa-calendar fa-fw w3-margin-right"></i>Jan 2015 - <span class="w3-tag w3-indigo w3-round">Current</span></h6>
          <p>{{ data.workexper_descrip }} </p>
          <hr>
        </div>
        <div class="w3-container">
          <h5 class="w3-opacity"><b>{{ data.second_experience }}</b></h5>
          <h6 class="w3-text-indigo"><i class="fa fa-calendar fa-fw w3-margin-right"></i>Mar 2012 - Dec 2014</h6>
          <p>Consectetur adipisicing elit. Praesentium magnam consectetur vel in deserunt aspernatur est reprehenderit sunt hic. Nulla tempora soluta ea et odio, unde doloremque repellendus iure, iste.</p>
          <hr>
        </div>
        <div class="w3-container">
          <h5 class="w3-opacity"><b>{{ data.third_experience }}</b></h5>
          <h6 class="w3-text-indigo"><i class="fa fa-calendar fa-fw w3-margin-right"></i>Jun 2010 - Mar 2012</h6>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. </p><br>
        </div>
      </div>

      <div class="w3-container w3-card w3-white">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-certificate fa-fw w3-margin-right w3-xxlarge w3-text-indigo"></i>{{ data.education }}</h2>
        <div class="w3-container">
          <h5 class="w3-opacity"><b>{{ data.primaryschool }}</b></h5>
          <h6 class="w3-text-indigo"><i class="fa fa-calendar fa-fw w3-margin-right"></i>Forever</h6>
          <p>Valedictorian</p>
          <hr>
        </div>
        <div class="w3-container">
          <h5 class="w3-opacity"><b>{{ data.secondaryschool }}</b></h5>
          <h6 class="w3-text-indigo"><i class="fa fa-calendar fa-fw w3-margin-right"></i>2013 - 2015</h6>
          <p>Valedictorian</p>
          <hr>
        </div>
        <div class="w3-container">
          <h5 class="w3-opacity"><b>{{ data.tertiaryschool }}</b></h5>
          <h6 class="w3-text-indigo"><i class="fa fa-calendar fa-fw w3-margin-right"></i>2010 - 2013</h6>
          <p>Bachelor Degree</p><br>
        </div>
      </div>

    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
  <!-- End Page Container -->
</div>

<footer class="w3-container w3-indigo w3-center w3-margin-top">
  <p>Find me on social media.</p>
  <i class="fa fa-facebook-official w3-hover-opacity"></i>
  <i class="fa fa-instagram w3-hover-opacity"></i>
  <i class="fa fa-snapchat w3-hover-opacity"></i>
  <i class="fa fa-pinterest-p w3-hover-opacity"></i>
  <i class="fa fa-twitter w3-hover-opacity"></i>
  <i class="fa fa-linkedin w3-hover-opacity"></i>
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>


</body></html>

pds/cvprof/templates/cvprof/prof.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0057)https://www.w3schools.com/w3css/tryw3css_templates_cv.htm -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Django App!</title>

<meta name="viewport" content="width=device-width, initial-scale=1">

<link rel="stylesheet" href="{% static 'cvprof/src/w3.css' %}">
<link rel="stylesheet" href="{% static 'cvprof/src/css.css' %}">
<link rel="stylesheet" href="{% static 'cvprof/src/f/css/font-awesome.min.css' %}">

<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
</style>
</head>
<body class="w3-light-grey">

<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1400px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
    <div class="w3-row">      
        <div class="w3-container">
            <div class="w3-container  w3-card w3-white w3-margin-bottom">
              <div class="w3-bar w3-padding-small">
                <a href="{% url 'cvprof:profiles' %}" class="w3-bar-item w3-button w3-text-teal"> <i class="fa fa-address-book fa-fw w3-margin-left w3-large " aria-hidden="true"></i>Lists Of Names</a>
                <a href="http://127.0.0.1:8000/admin/cvprof/cvmodel/add/" class="w3-bar-item w3-button w3-text-teal">Add New Cv Model</a>
                <a href="http://127.0.0.1:8000/admin/" class="w3-bar-item w3-button w3-text-teal">Admin Page</a>
              </div>
                
            </div>     
        </div>

        <div class="w3-container">
            <div class="w3-container  w3-card w3-white w3-margin-bottom">
               <h2>List of Profile ( )</h2>
              
               <ul  class="w3-ul">
                {% for itm in records %}
                    <li class="w3-bar">
                      <span onclick="this.parentElement.style.display='none'"
                      class="w3-bar-item w3-button w3-xlarge w3-right">&times;</span>
                      
                      <img src="{% static 'cvprof/src/img/lisa.jpeg' %}" class="w3-bar-item w3-circle" style="width:85px">
                      <div class="w3-bar-item">
                        <span class="w3-large">
                          <a href="{% url 'cvprof:index' itm.id %}" class="w3-bar-item w3-button w3-hover-none w3-border-white w3-bottombar w3-hover-border-teal">{{ itm.fullname }}</a>
                        </span>                        
                      </div>
                  </li>
                {% endfor %}
                </ul>
                

            </div>     
        </div>

    </div>

  <!-- End Grid -->
  </div>
  
  <!-- End Page Container -->
</div>

<footer class="w3-container w3-teal w3-center w3-margin-top">
  <p>Find me on social media.</p>
  <i class="fa fa-facebook-official w3-hover-opacity"></i>
  <i class="fa fa-instagram w3-hover-opacity"></i>
  <i class="fa fa-snapchat w3-hover-opacity"></i>
  <i class="fa fa-pinterest-p w3-hover-opacity"></i>
  <i class="fa fa-twitter w3-hover-opacity"></i>
  <i class="fa fa-linkedin w3-hover-opacity"></i>
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>


</body>

</html>